### PR TITLE
fixed bug so that AVR boards also work

### PR DESCRIPTION
**Pull request by lutzerb**
Hi,

I wanted to use the code on a CONTROLLINO board which is basically a Arduino Mega in a DIN rail enclosure.

For this I needed to make it work on an AVR architecture.
The issue was not a bug in the AVR time.h library but rather a different logic of it compared to other architectures. 

time.h on AVR starts on 1st of January 2020, not in 1st of January 1970 like normal unix timestamps. 

See the documentation (https://www.nongnu.org/avr-libc/user-manual/group__avr__time.html):

> Though not specified in the standard, it is often expected that time_t is a signed integer representing an offset in seconds from Midnight Jan 1 1970... i.e. 'Unix time'. This implementation uses an unsigned 32 bit integer offset from Midnight Jan 1 2000. The use of this 'epoch' helps to simplify the conversion functions, while the 32 bit value allows time to be properly represented until Tue Feb 7 06:28:15 2136 UTC. The macros UNIX_OFFSET and NTP_OFFSET are defined to assist in converting to and from Unix and NTP time stamps.

Furthermore I changed the code how to make the 32bit NTP timestamp from the received bytes. I am not sure if this is really needed, I took this from somewhere and it worked on my µC.

### CODE REVIEW

**Comment by sstaub** [comment]
Did you tested for ARM or ESP?

**Comment by lutzerb** [comment]
It works fine on my  ATmega2560

I have an ESP32 lying around, I can try there as well

Am Sa., 3. Dez. 2022 um 12:25 Uhr schrieb Stefan Staub <
***@***.***>:

**Comment by sstaub** [comment]
Let me know if it works on ESP. This is not a bug from AVR, this change should avoid on overflow in 2038.

**Comment by lutzerb** [comment]
I tried now using a ESP32-C3 and again on my ATmega2560-based board. Works fine in both cases.

**Comment by sstaub** [comment]
I will test on an ARM based board. I want also to make some API change, because I don't use getter/setter API. If it works I will pull. Thank you.

**Comment by sstaub** [comment]
Your changes will include in 1.7, the getter are simply ntp() and etc()

**Pull request closed without merging**
